/*
 * NOTE: This class requires gRPC stubs generated by Maven.
 * Since 'mvn' is not installed in this environment, this code is commented out to allow compilation.
 *
 * TO ENABLE:
 * 1. Install Maven.
 * 2. Run `mvn clean compile` in the java/ directory.
 * 3. Uncomment the code below.
 */

package ai.acie.server.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import jakarta.annotation.PreDestroy;
import java.util.List;
import java.util.Map;

// import acie.InferenceServiceGrpc;
// import acie.Acie;
// import io.grpc.ManagedChannel;
// import io.grpc.ManagedChannelBuilder;

@Service
public class GrpcInferenceClient {

    // private final ManagedChannel channel;
    // private final InferenceServiceGrpc.InferenceServiceBlockingStub blockingStub;

    public GrpcInferenceClient(@Value("${acie.inference.host:localhost}") String host,
            @Value("${acie.inference.port:50051}") int port) {
        // this.channel = ManagedChannelBuilder.forAddress(host, port)
        // .usePlaintext() // Disable TLS for internal communication
        // .build();
        // this.blockingStub = InferenceServiceGrpc.newBlockingStub(channel);
        System.out.println("WARNING: gRPC Client is disabled because stubs are missing.");
    }

    public Object infer(String modelVersion, List<Float> observation, Map<String, Float> intervention,
            String requestId) {
        /*
         * Acie.InferenceRequest request = Acie.InferenceRequest.newBuilder()
         * .setModelVersion(modelVersion)
         * .addAllObservation(observation)
         * .putAllIntervention(intervention)
         * .setRequestId(requestId)
         * .build();
         * 
         * return blockingStub.counterfactualInference(request);
         */
        throw new UnsupportedOperationException("gRPC Client is disabled. Please compile with Maven.");
    }

    @PreDestroy
    public void shutdown() throws InterruptedException {
        // channel.shutdown().awaitTermination(5, TimeUnit.SECONDS);
    }
}
